# From https://github.com/eeholmes/readthedoc-test/blob/main/.github/workflows/docs_pages.yml
name: docs

# execute this workflow automatically when a we push to main
on:
  push:
    branches: [ docs_ms ]
  workflow_dispatch:

jobs:

  build_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: docs_ms

      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          path: gh-pages
          ref: gh-pages

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd ./docs_ms
          python -m pip install .[docs]
      - name: Make the Sphinx docs
        run: |
          cd ./docs_ms/docsrc
          make clean
          make github
      - name: Commit changes to docs
        run: |
          cd ./gh-pages
          cp -R ../docs_ms/docs/* ./
          git config --local user.email ""
          git config --local user.name "github-actions"
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "auto: Rebuild docs."
            git  push
          else
            echo No commit made because the docs have not changed.
          fi